spring.application.name=FastAndFuriousBurguer

spring.datasource.url=jdbc:mysql://172.16.0.30:3306/rms_fastfurious?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=rms
spring.datasource.password=2diSenai
spring.jpa.show-sql=True